In [2]:
import numpy as np
import pandas as pd

In [3]:
# How likely is it that you roll doubles when rolling two dice?

In [42]:
outcomes = [1, 2, 3, 4, 5, 6]
n_simulations = 10_000
n_trails = 2
die1 = np.random.choice(outcomes, size=n_simulations)
die2 = np.random.choice(outcomes, size=n_simulations)

(die1 == die2).mean()

0.1649

In [ ]:
# If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [21]:
#1 for heads, 0 for tails
outcomes = [1, 0]
n_simulations = 10_000
n_trials = 8
flips = np.random.choice(outcomes,  size=(n_simulations, n_trials))

In [24]:
results = flips.sum(axis=1)

In [26]:
(results == 3).mean()

0.2119

In [27]:
(results >3).mean()

0.6399

In [28]:
# There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup.
# Assuming that Codeup randomly selects an alumni to put on a billboard,
# what are the odds that the two billboards I drive past both have data science students on them?

In [32]:
# 1 for Data science
# 0 for Web Dev
outcomes = [1, 0]
n_simulations = 10_000
n_trials = 2
billboard = np.random.choice(outcomes,  size=(n_simulations, n_trials), p=[0.25, 0.75])

In [33]:
billboard

array([[1, 1],
       [0, 0],
       [0, 0],
       ...,
       [1, 0],
       [0, 1],
       [0, 0]])

In [34]:
results = billboard.sum(axis=1)

In [35]:
results

array([2, 0, 0, ..., 1, 1, 0])

In [36]:
(results == 2).mean()

0.0617

In [ ]:
# Codeup students buy, on average, 3 poptart packages (+- 1.5) a day from the snack vending machine.
# If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be
# able to buy some poptarts on Friday afternoon?

In [62]:
n_simulations = 10_000

In [63]:
n_trials = 5

In [66]:
results = np.random.normal(loc = 3, scale = 1.5, size=(n_simulations, n_trials))

In [67]:
np.rint(results)

array([[4., 3., 3., 5., 2.],
       [3., 3., 2., 4., 3.],
       [1., 3., 3., 5., 4.],
       ...,
       [5., 5., 3., 3., 2.],
       [2., 3., 1., 3., 5.],
       [3., 3., 2., 3., 1.]])

In [68]:
results = results.sum(axis=1)

In [69]:
results

array([16.34190559, 14.91340453, 15.81514084, ..., 17.73629545,
       14.98901724, 11.00877221])

In [70]:
(results < 17).mean()

0.7211

In [60]:
# Compare Heights

# Men have an average height of 178 cm and standard deviation of 8cm.
# Women have a mean of 170, sd = 6cm.
# Since you have means and standard deviations, you can use np.random.normal to generate observations.
# If a man and woman are chosen at random, P(woman taller than man)?

In [71]:
n_simulations = 10_000

In [72]:
men = np.random.normal(loc = 178, scale = 8, size=n_simulations)
women = np.random.normal(loc = 170, scale = 6, size=n_simulations)

In [103]:
women > men

array([False,  True, False, ..., False,  True, False])

In [74]:
(women > men).mean()

0.2083

In [ ]:
# When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails.
# What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

# What is the probability that we observe an installation issue within the first 150 students that download anaconda?

# How likely is it that 450 students all download anaconda without an issue?

In [205]:
# fails =1, success =0
outcomes = [1, 0]
n_simulations = 10_000
n_trails = 50
fails = np.random.choice(outcomes,  size=(n_simulations, n_trails), p=[.004, .996])

In [206]:
fails = fails.sum(axis=1)

In [207]:
fails

array([0, 0, 1, ..., 0, 0, 0])

In [208]:
1- (fails >=1).mean()

0.8123

In [209]:
# fails =1, success =0
outcomes = [1, 0]
n_simulations = 10_000
n_trails = 100
fails = np.random.choice(outcomes,  size=(n_simulations, n_trials), p=[.004, .996])
fails = fails.sum(axis=1)
1 - (fails >=1).mean()

0.9115

In [210]:
# fails =1, success =0
outcomes = [1, 0]
n_simulations = 10_000
n_trails = 150
fails = np.random.choice(outcomes,  size=(n_simulations, n_trials), p=[.004, .996])
fails = fails.sum(axis=1)
1 - (fails >=1).mean()

0.9087

In [211]:
outcomes = [1, 0]
n_simulations = 10_000
n_trails = 450
fails = np.random.choice(outcomes,  size=(n_simulations, n_trials), p=[.004, .996])
fails = fails.sum(axis=1)
1 - (fails >=1).mean()

0.9166

In [104]:
# There's a 70% chance on any given day that there will be at least one food truck at Travis Park.
#However, you haven't seen a food truck there in 3 days. How unlikely is this?

# How likely is it that a food truck will show up sometime this week?

In [105]:
# 1 is True, 0 is false
outcomes = [1, 0]
n_simulations = 10_000
n_trial = 3
food_truck = np.random.choice(outcomes,  size=(n_simulations, n_trials), p=[.70, .30])
food_truck = food_truck.sum(axis=1)

In [109]:
print(f"The likely change of not seeing a food truck in 3 days is {(food_truck == 0).mean()}")

The likely change of not seeing a food truck in 3 days is 0.0028


In [110]:
# 1 is True, 0 is false
outcomes = [1, 0]
n_simulations = 10_000
n_trial = 7
food_truck = np.random.choice(outcomes,  size=(n_simulations, n_trials), p=[.70, .30])
food_truck = food_truck.sum(axis=1)
print(f"The likely change of not seeing a food truck in 7 days is {(food_truck == 0).mean()}")

The likely change of not seeing a food truck in 7 days is 0.0023


In [102]:
# If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [251]:
# 1 is True, 0 is false
outcomes = list(range(1, 366))
n_simulations = 10_000
n_trials = 23
food_truck = np.random.choice(outcomes,  size=(n_simulations, n_trials))

In [252]:
df = pd.DataFrame(food_truck)

In [253]:
df

0    1    2    3    4    5    6    7    8    9   ...   13   14   15  \
0      28   54  171  363  241  333  113   24   97  194  ...  154   21  201   
1     281  243   69  196  313   58  126  338  165  225  ...   39   37  167   
2     197  254  337   38   36   96   79  339   33  301  ...  183  277  231   
3     121   83  280  276  275  185  153  227  341  206  ...  199  337   95   
4     126  186  161   25  206   33  155  202  207  159  ...    1  104  180   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995   99   45  289  158   14  250   51  192   85   63  ...  128  172   75   
9996   42  219  234   88  160  355   99   47   78  275  ...   23  226  301   
9997  343  134  124  133  360  146  357  340    5  141  ...  277  107   72   
9998  365   32    9  210  300  172  234   22  160   89  ...  323  116  259   
9999  304  185  346   81   62   49  105  148  296  365  ...  233  365  190   

       16   17   18   19   20   21   22  
0     305  149  297  295  322   83  362  
1     214   10  339   68  321  197  228  
2     201  191  267  206  178  111  188  
3     257  173  187  159   80  255  334  
4     342   25  213   27   73  313  234  
...   ...  ...  ...  ...  ...  ...  ...  
9995  246  250  284   83   56  205  218  
9996  365   84   95  210  187  305  344  
9997  118  138  284  284  304  233   97  
9998  297    6  215  218   48   98  188  
9999  350  211  123   96  265  315   15  

[10000 rows x 23 columns]

In [254]:
no_one_shares_bday = df.apply(lambda row: row.is_unique , axis=1)

In [255]:
no_one_shares_bday

0       False
1        True
2        True
3        True
4       False
        ...  
9995    False
9996     True
9997    False
9998     True
9999    False
Length: 10000, dtype: bool

In [256]:
(no_one_shares_bday == True).mean()

0.5005

In [260]:
# 1 is True, 0 is false for 20 students
outcomes = list(range(1, 366))
n_simulations = 10_000
n_trials = 20
food_truck = np.random.choice(outcomes,  size=(n_simulations, n_trials))
df = pd.DataFrame(food_truck)
no_one_shares_bday = df.apply(lambda row: row.is_unique , axis=1)
(no_one_shares_bday == True).mean()

0.5947

In [262]:
# 1 is True, 0 is false For 40 students
outcomes = list(range(1, 366))
n_simulations = 10_000
n_trials = 40
food_truck = np.random.choice(outcomes,  size=(n_simulations, n_trials))
df = pd.DataFrame(food_truck)
no_one_shares_bday = df.apply(lambda row: row.is_unique , axis=1)
(no_one_shares_bday == True).mean()

0.108